
DROP TABLE IF EXISTS  USER_TBL;
DROP TABLE IF EXISTS  COMMENT_TBL;
DROP TABLE IF EXISTS  FEED_TBL;


CREATE USER IF NOT EXISTS "SA" SALT '16ead34d548dbf6a' HASH '4a70bbab87b9b3ff05e0d1e2a8b9d41050fe129b93bcd052dd5d217eb419fdfe' ADMIN;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "PUBLIC"."COMMENT_TBL"(
    "ID" INTEGER NOT NULL,
    "MESSAGE" VARCHAR(255),
    "POSTED_DATE" TIMESTAMP,
    "COMMENTED_BY_ID" INTEGER,
    "FEEDS_ENTITY_ID" INTEGER
);
ALTER TABLE "PUBLIC"."COMMENT_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT_TBL;
CREATE MEMORY TABLE "PUBLIC"."FEED_TBL"(
    "ID" INTEGER NOT NULL,
    "FEED_DETAIL" VARCHAR(255),
    "LIKES" INTEGER,
    "POSTED_ON" TIMESTAMP,
    "USER_ID" INTEGER
);
ALTER TABLE "PUBLIC"."FEED_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FEED_TBL;
CREATE MEMORY TABLE "PUBLIC"."USER_TBL"(
    "ID" INTEGER NOT NULL,
    "AGE" INTEGER,
    "DISPLAY_PICTURE" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_TBL;
ALTER TABLE "PUBLIC"."COMMENT_TBL" ADD CONSTRAINT "PUBLIC"."FK2PR2648UGF69QCBWNAMTUTJH5" FOREIGN KEY("COMMENTED_BY_ID") REFERENCES "PUBLIC"."USER_TBL"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."COMMENT_TBL" ADD CONSTRAINT "PUBLIC"."FKGQM1RXT89726BWLSYYBP3JL4F" FOREIGN KEY("FEEDS_ENTITY_ID") REFERENCES "PUBLIC"."FEED_TBL"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."FEED_TBL" ADD CONSTRAINT "PUBLIC"."FKOHU890SFXVYOKIP9TMWTAOPFN" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_TBL"("ID") NOCHECK;